spring:
    datasource:
        driverClassName: org.h2.Driver
        jdbc-url: jdbc:h2:mem:spring-quartz;DB_CLOSE_ON_EXIT=FALSE
        password: ''
        username: sa
    quartz:
        jdbc:
            initialize-schema: always
        job-store-type: jdbc
using:
    spring:
        schedulerFactory: true
