spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.99.107:30800/spring-quartz?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        password: 'password'
        username: root    
    quartz:
        jdbc:
            initialize-schema: always
        job-store-type: jdbc
using:
    spring:
        schedulerFactory: true
